### ISSUE TITLE
"Unknown Error" thrown by Node.js

### ISSUE THREAD

**Issue by nbutler77** [lirbank/star-amqp#2]
We're getting an error message similar to the one described [here](https://github.com/squaremo/amqp.node/issues/441); trace looks like:
```
events.js:167
throw er; // Unhandled 'error' event
^
Error: Unexpected close
at succeed (/home/centos/flirmachinelearning/node_modules/amqplib/lib/connection.js:271:13)
at onOpenOk (/home/centos/flirmachinelearning/node_modules/amqplib/lib/connection.js:253:5)
at /home/centos/flirmachinelearning/node_modules/amqplib/lib/connection.js:166:32
at /home/centos/flirmachinelearning/node_modules/amqplib/lib/connection.js:160:12
at Socket.recv (/home/centos/flirmachinelearning/node_modules/amqplib/lib/connection.js:498:12)
at Object.onceWrapper (events.js:273:13)
at Socket.emit (events.js:182:13)
at Socket.EventEmitter.emit (domain.js:441:20)
at emitReadable_ (_stream_readable.js:534:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
at Connection.emit (events.js:182:13)
at Connection.EventEmitter.emit (domain.js:441:20)
at Connection.C.onSocketError (/home/centos/flirmachinelearning/node_modules/amqplib/lib/connection.js:352:10)
at Socket.emit (events.js:187:15)
at Socket.EventEmitter.emit (domain.js:441:20)
at endReadableNT (_stream_readable.js:1094:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
```

It seems like updating amqplib to 0.5.3 may address the issue. Can you do that?

Thanks,

Neal Butler

**Comment by lirbank** [comment]
I've published a new beta version with the `amqplib` dependency upgraded to the latest version, try installing `star-amqp@next` or `star-amqp@0.0.7-beta.0` and see if it helps.
